version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: typeahead-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: typeahead
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped


  redis-node-1:
    image: redis:7-alpine
    container_name: typeahead-redis-1
    ports:
      - "6379:6379"
    restart: unless-stopped

  redis-node-2:
    image: redis:7-alpine
    container_name: typeahead-redis-2
    ports:
      - "6380:6379"
    restart: unless-stopped

  redis-node-3:
    image: redis:7-alpine
    container_name: typeahead-redis-3
    ports:
      - "6381:6379"
    restart: unless-stopped

volumes:
  postgres_data:




